version: '3'

networks:
  app-network:

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data
    networks:
      - app-network
  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-prod
    networks:
      - app-network